public enum Job {// just an enum to make things more organised in the code so i
	// am not using strings

	MEMBERADDED, QUIT, LOGOUT, LOGIN, REGISTER, MESSAGE, REQUESTS, REMOVEMEMBER, JOIN, CREATEGROUP, TOADMIN, MESSAGEGROUPFAILED, ADDADMIN, FORCEDQUIT, ADDMEMBER, MESSAGEGROUP, EMPTY, CREATEGROUPFAILED, MEMBERNOTADDED, SHOWGROUPS
}
